# Site settings
title: Marzcorp
email: coreyling@ionshard.com 
description: > # this means to ignore newlines until "baseurl:"
  Marzcorp Oil & Gas Inc. owns 100% interest in the in the Matapédia Valley, Gaspésie, Quebec.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://marzcorp.github.io" # the base hostname & protocol for your site
twitter_username: kasukoxr
github_username:  kasuko
google_analytics: UA-XXXXX-X

# Build settings
markdown: kramdown
